grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
      min_samples_leaf: 3
      max_features: 'sqrt'
      n_estimators: 100
      max_depth: 2
    search_param_grid: 
      min_samples_leaf: 
      - 3
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 2
      max_features: 'sqrt'
      n_estimators: 100
      max_depth: 2
    search_param_grid:
      min_samples_leaf:
      - 2
      - 8
      - 15
      - 10
      max_features:
      - 5
      - 7
      - "sqrt"
      - "log2"
      n_estimators:
      - 100
      - 200
      - 500
      - 1000
      max_depth:
      - 5
      - 8
      - 10